version: '3.3'

services:
  postgres-database:
    image: postgres:13
    environment:
      - POSTGRES_DB=notesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql